### ISSUE TITLE
Some questions about the trace simulator

### ISSUE THREAD

**Issue by xiechengsheng** [camsas/firmament#57]
@ms705 Hi, I read yours OSDI paper and see that you used the google trace workload to test the firmament scheduler's task placement latency and the job response time. And I see the trace data csv file includes job and task's metadata, so my question is:

1. Can the google trace data be used to test the task/job finish time in one machine? The simulator is just a process that simulates the scheduler and can't simulate the task/job execution time, is my thought right?
2. I saw your [source sim code](https://github.com/camsas/firmament/tree/master/src/sim), can the new scheduler(eg. mesos scheduler) be added to yours simlulator by extending `src/sim/simulator_bridge.cc`? 
3. So, if I want to test a new scheduler's(eg. mesos) task placement latency, do I have to write the simulator codes for this scheduler? Or can I just use yours simulator to test the scheduler's performance? And if there are more details about how to write a new simulator for one's own scheduler by using google trace data, please let me know.

Thank you very much!

**Comment by ms705** [comment]
Hi @xiechengsheng,

Sorry for the late response -- I must have somehow missed this issue. 

Here are the answers to your questions:
 1. The simulator does simulate task execution, but takes the task runtime from the trace. It has events for task and job completion, but they are based on the real runtimes recorded in the trace, so they do not reflect the uncertainty and variance in a real execution. That said, @ICGog and @michaelschaarschmidt have been working on extensions that model the interference between co-located tasks on a machine.
 2. Yes, that could work, although `SimulatorBridge` is probably not the best interface for doing this -- it would require you writing a lot of code on the Mesos side to get the interaction to work. A better way to do this would be to implement a class that implements `SchedulerInterface` (see `SimpleScheduler` and `FlowScheduler` for examples; they're both extensions of `EventDrivenScheduler`), and to then model the Mesos scheduler's behaviour in that class, reusing logic from Mesos as appropriate.
 3. If you manage to use `SchedulerInterface`, you would not have to write any simulation code  (or at least, very minimal code to hook in your new class). You do have to write the simulated scheduling logic for the new scheduler you're adding, however.

Hope that helps!
