### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by CHENLIELIE** [camsas/firmament#59]
hello Malte and everyone, I got a problem when I build the firmament. After 'make' in build dir, it return 'flowlessly-download error', but, when I use 'git clone https://github.com/ICGog/Flowlessly.git', it works well. The flowlessly-download-err.log as follows: 
fatal: unable to access 'https://github.com/ICGog/Flowlessly.git/': gnutls_handshake() failed: Error in the pull function.
Besides, when downloading the grpc, it also give the likely fault. I have try many times but failed.

**Comment by ms705** [comment]
Hi @CHENLIELIE,

This most likely sounds like a network issue at your end, unfortunately -- for example, a firewall that's intercepting or rate-limiting HTTPS requests. The build scripts do clone a lot of repositories in quick succession, which might trigger these kinds of things.

Where are you trying this from? Does it persist if you run on a cloud network, e.g., on EC2?

**Comment by CHENLIELIE** [comment]
Thanks for your reply, Malte. Maybe it's my network issue, sometime, Flowlessly can be download, sometime it failed. But the grpc always can't be download, I found that a ‘https://‘ can't be accessed in my environment. so, I used the docker instead, but when I execute 'python job_submit.py localhost 8080 /bin/sleep 60', it failed, too. It gives the 'ImportError: cannot import name label_pb2', I found the file task_desc_pb2.py in '/firmament/scripts/job/base' has this line 'from base import label_pb2 as base_dot_label__pb2', but my base directory has't the file of 'label_pb2.py'. what's the problem?

**Comment by ms705** [comment]
This sounds like the protobufs aren't compiled for Python. Try running `make` in the `scripts/job/job_submit.py` directory, maybe?

**Comment by ms705** [comment]
@CHENLIELIE Did this problem get resolved?

**Comment by CHENLIELIE** [comment]
sorry for reply, Malte. I also think that the problem is caused by protobufs and Python, but I don't know how to solve it. I have try build new python  and build new protobufs for python. Besides, there are no makefile under scripts/job/job_submit.py directory, it's right?

**Comment by ms705** [comment]
The relevant code in the CMake build system is here:
https://github.com/camsas/firmament/blob/master/scripts/job/CMakeLists.txt#L9-L14

This should generate a Makefile in `build/scripts/job` (i.e., inside the build hierarchy, not the main code directories).

What platform are you running on? The build system will try to use its own local version of Protobuf3 to compile the protocol buffers, but we've seen issues with fallback to system-wide installations of Protobuf2 in the past.

**Comment by CHENLIELIE** [comment]
Thanks for your help, Malte. I have built the firmament successfully. I installed other boost library, it worked well, thanks.

**Comment by ms705** [comment]
Great! Closing this.
